# .github/workflows/update-files.yml  
name: Update files in current branch

permissions:
  contents: write  # Needed for git push
on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main           # (or any branch you want to act on)

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the current branch
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0         # ensures full branch history
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Make file changes
      - name: Modify files
        run: |
          echo "Last updated at $(date)" > timestamp.txt
          mkdir -p reports
          pwd
          ls -l
          echo "contents of a2" 
          

    
