# .github/workflows/update-files.yml
name: Update files in current branch

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main           # (or any branch you want to act on)

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the current branch
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0         # ensures full branch history
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 2: Make file changes
      - name: Modify files
        run: |
          echo "Last updated at $(date)" > timestamp.txt
          mkdir -p reports
          echo "Automated report generated on $(date)" > reports/summary.txt

      # Step 3: Commit changes
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && echo "No changes to commit" || git commit -m "Auto-update files [skip ci]"

      # Step 4: Push changes
      - name: Push changes
        run: |
          git push
